//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataRelational.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataRelational.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_Boolean] ON [dbo].[List_Boolean] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Boolean {
            get {
                return ResourceManager.GetString("Index_IDX_List_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_BooleanValue] ON [dbo].[List_BooleanValue] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_BooleanValue {
            get {
                return ResourceManager.GetString("Index_IDX_List_BooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_Byte] ON [dbo].[List_Byte] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Byte {
            get {
                return ResourceManager.GetString("Index_IDX_List_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_ByteValue] ON [dbo].[List_ByteValue] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_ByteValue {
            get {
                return ResourceManager.GetString("Index_IDX_List_ByteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_DateTime] ON [dbo].[List_DateTime] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_DateTime {
            get {
                return ResourceManager.GetString("Index_IDX_List_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_DateTimeValue] ON [dbo].[List_DateTimeValue] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_DateTimeValue {
            get {
                return ResourceManager.GetString("Index_IDX_List_DateTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_Decimal] ON [dbo].[List_Decimal] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Decimal {
            get {
                return ResourceManager.GetString("Index_IDX_List_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_DecimalValue] ON [dbo].[List_DecimalValue] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_DecimalValue {
            get {
                return ResourceManager.GetString("Index_IDX_List_DecimalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_Double] ON [dbo].[List_Double] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Double {
            get {
                return ResourceManager.GetString("Index_IDX_List_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_DoubleValue] ON [dbo].[List_DoubleValue] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_DoubleValue {
            get {
                return ResourceManager.GetString("Index_IDX_List_DoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_Guid] ON [dbo].[List_Guid] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Guid {
            get {
                return ResourceManager.GetString("Index_IDX_List_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_GuidValue] ON [dbo].[List_GuidValue] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_GuidValue {
            get {
                return ResourceManager.GetString("Index_IDX_List_GuidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_Int16] ON [dbo].[List_Int16] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Int16 {
            get {
                return ResourceManager.GetString("Index_IDX_List_Int16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_Int16Value] ON [dbo].[List_Int16Value] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Int16Value {
            get {
                return ResourceManager.GetString("Index_IDX_List_Int16Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_Int32] ON [dbo].[List_Int32] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Int32 {
            get {
                return ResourceManager.GetString("Index_IDX_List_Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_Int32Value] ON [dbo].[List_Int32Value] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Int32Value {
            get {
                return ResourceManager.GetString("Index_IDX_List_Int32Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_Int64] ON [dbo].[List_Int64] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Int64 {
            get {
                return ResourceManager.GetString("Index_IDX_List_Int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_Int64Value] ON [dbo].[List_Int64Value] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Int64Value {
            get {
                return ResourceManager.GetString("Index_IDX_List_Int64Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_Single] ON [dbo].[List_Single] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_Single {
            get {
                return ResourceManager.GetString("Index_IDX_List_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_SingleValue] ON [dbo].[List_SingleValue] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_SingleValue {
            get {
                return ResourceManager.GetString("Index_IDX_List_SingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE NONCLUSTERED INDEX [IDX_List_String] ON [dbo].[List_String] 
        ///(
        ///	[_DataObjectTypeId] ASC,
        ///	[ObjectId] ASC,
        ///	[ObjectRevisionId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_String {
            get {
                return ResourceManager.GetString("Index_IDX_List_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE CLUSTERED INDEX [IDX_List_StringValue] ON [dbo].[List_StringValue] 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY].
        /// </summary>
        internal static string Index_IDX_List_StringValue {
            get {
                return ResourceManager.GetString("Index_IDX_List_StringValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DataObjectField](
        ///	[_Id] [int] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[FieldName] [varchar](255) NOT NULL,
        ///	[_DataObjectFieldTypeId] [tinyint] NOT NULL,
        ///	[FieldLength] [int] NOT NULL,
        ///	[Unicode] [bit] NOT NULL,
        /// CONSTRAINT [PK_DataObjectField] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_DataObjectField {
            get {
                return ResourceManager.GetString("Table_DataObjectField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DataObjectFieldType](
        ///	[_Id] [tinyint] NOT NULL,
        ///	[Name] [varchar](255) NOT NULL,
        /// CONSTRAINT [PK_DataObjectFieldType] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///INSERT INTO DataObjectFieldType(_Id, Name) VALUES(0, &apos;Boolean&apos;)
        ///INSERT INTO DataObjectFieldType(_Id, Name) VALUES(1, &apos;Byte&apos;)
        ///INSERT INTO DataObjectFieldType(_Id, Name)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_DataObjectFieldType {
            get {
                return ResourceManager.GetString("Table_DataObjectFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DataObjectIndex](
        ///	[_Id] [int] NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        ///	[IndexName] [varchar](255) NOT NULL,
        ///	[Ascending] [bit] NOT NULL,
        /// CONSTRAINT [PK_DataObjectIndex] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_DataObjectFieldId] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///GO
        ///ALTER TABLE [dbo].[DataObjectIndex]  WI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_DataObjectIndex {
            get {
                return ResourceManager.GetString("Table_DataObjectIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DataObjectRelationship](
        ///	[ParentId] [bigint] NOT NULL,
        ///	[ParentTypeId] [smallint] NOT NULL,
        ///	[ParentFieldId] [int] NOT NULL,
        ///	[ChildId] [bigint] NOT NULL,
        ///	[ChildTypeId] [smallint] NOT NULL,
        ///	[BeginDate] [datetime] NOT NULL,
        ///	[EndDate] [datetime] NOT NULL
        ///) ON [PRIMARY]
        ///GO
        ///ALTER TABLE [dbo].[DataObjectRelationship]  WITH CHECK ADD  CONSTRAINT [FK_DataObjectRelationship_DataObjectField] FOREIGN KEY([ParentFieldId])
        ///REFERENCES [dbo].[DataObjectField] ([_Id])
        ///GO
        ///ALTER TABLE [d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_DataObjectRelationship {
            get {
                return ResourceManager.GetString("Table_DataObjectRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[DataObjectType](
        ///	[_Id] [smallint] IDENTITY(1,1) NOT NULL,
        ///	[TypeName] [varchar](255) NULL,
        ///	[TableName] [varchar](255) NULL,
        /// CONSTRAINT [PK_ObjectType] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY].
        /// </summary>
        internal static string Table_DataObjectType {
            get {
                return ResourceManager.GetString("Table_DataObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Boolean](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_Boolean] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_Boolean]  WITH CHECK ADD  CONS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Boolean {
            get {
                return ResourceManager.GetString("Table_List_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_BooleanValue](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [bit] NULL,
        /// CONSTRAINT [PK_List_BooleanValue] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_BooleanValue]  WITH CHECK ADD  CONSTRAINT [FK_List_BooleanValue_List_Boolean] FOREIGN KEY([_Id])
        ///REFERENCES [dbo]. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_BooleanValue {
            get {
                return ResourceManager.GetString("Table_List_BooleanValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Byte](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_Byte] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_Byte]  WITH CHECK ADD  CONSTRAINT [F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Byte {
            get {
                return ResourceManager.GetString("Table_List_Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_ByteValue](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [tinyint] NULL,
        ///	 CONSTRAINT [PK_List_ByteValue] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_ByteValue]  WITH CHECK ADD  CONSTRAINT [FK_List_ByteValue_List_Byte] FOREIGN KEY([_Id])
        ///REFERENCES [dbo].[List_Byte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_ByteValue {
            get {
                return ResourceManager.GetString("Table_List_ByteValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_DateTime](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_DateTime] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_DateTime]  WITH CHECK ADD  C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_DateTime {
            get {
                return ResourceManager.GetString("Table_List_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_DateTimeValue](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [datetime] NULL,
        ///	 CONSTRAINT [PK_List_DateTimeValue] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_DateTimeValue]  WITH CHECK ADD  CONSTRAINT [FK_List_DateTimeValue_List_DateTime] FOREIGN KEY([_Id])
        ///REFERE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_DateTimeValue {
            get {
                return ResourceManager.GetString("Table_List_DateTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Decimal](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_Decimal] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_Decimal]  WITH CHECK ADD  CONS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Decimal {
            get {
                return ResourceManager.GetString("Table_List_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_DecimalValue](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [decimal] NULL,
        ///	 CONSTRAINT [PK_List_DecimalValue] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_DecimalValue]  WITH CHECK ADD  CONSTRAINT [FK_List_DecimalValue_List_Decimal] FOREIGN KEY([_Id])
        ///REFERENCES [ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_DecimalValue {
            get {
                return ResourceManager.GetString("Table_List_DecimalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Double](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_Double] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_Double]  WITH CHECK ADD  CONSTRA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Double {
            get {
                return ResourceManager.GetString("Table_List_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_DoubleValue](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [float] NULL,
        ///	 CONSTRAINT [PK_List_DoubleValue] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_DoubleValue]  WITH CHECK ADD  CONSTRAINT [FK_List_DoubleValue_List_Double] FOREIGN KEY([_Id])
        ///REFERENCES [dbo].[L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_DoubleValue {
            get {
                return ResourceManager.GetString("Table_List_DoubleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Guid](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_Guid] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_Guid]  WITH CHECK ADD  CONSTRAINT [F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Guid {
            get {
                return ResourceManager.GetString("Table_List_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_GuidValue](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [uniqueidentifier] NULL,
        ///	 CONSTRAINT [PK_List_GuidValue] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_GuidValue]  WITH CHECK ADD  CONSTRAINT [FK_List_GuidValue_List_Guid] FOREIGN KEY([_Id])
        ///REFERENCES [dbo].[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_GuidValue {
            get {
                return ResourceManager.GetString("Table_List_GuidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Int16](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_Int16] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_Int16]  WITH CHECK ADD  CONSTRAINT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Int16 {
            get {
                return ResourceManager.GetString("Table_List_Int16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Int16Value](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [smallint] NULL,
        ///	 CONSTRAINT [PK_List_Int16Value] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_Int16Value]  WITH CHECK ADD  CONSTRAINT [FK_List_Int16Value_List_Int16] FOREIGN KEY([_Id])
        ///REFERENCES [dbo].[Lis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Int16Value {
            get {
                return ResourceManager.GetString("Table_List_Int16Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Int32](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_Int32] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_Int32]  WITH CHECK ADD  CONSTRAINT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Int32 {
            get {
                return ResourceManager.GetString("Table_List_Int32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Int32Value](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [int] NULL,
        ///	 CONSTRAINT [PK_List_Int32Value] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_Int32Value]  WITH CHECK ADD  CONSTRAINT [FK_List_Int32Value_List_Int32] FOREIGN KEY([_Id])
        ///REFERENCES [dbo].[List_Int [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Int32Value {
            get {
                return ResourceManager.GetString("Table_List_Int32Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Int64](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_Int64] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_Int64]  WITH CHECK ADD  CONSTRAINT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Int64 {
            get {
                return ResourceManager.GetString("Table_List_Int64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Int64Value](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [bigint] NULL,
        ///	 CONSTRAINT [PK_List_Int64Value] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_Int64Value]  WITH CHECK ADD  CONSTRAINT [FK_List_Int64Value_List_Int64] FOREIGN KEY([_Id])
        ///REFERENCES [dbo].[List_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Int64Value {
            get {
                return ResourceManager.GetString("Table_List_Int64Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_Single](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_Single] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_Single]  WITH CHECK ADD  CONSTRA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_Single {
            get {
                return ResourceManager.GetString("Table_List_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_SingleValue](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [real] NULL,
        ///	 CONSTRAINT [PK_List_SingleValue] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_SingleValue]  WITH CHECK ADD  CONSTRAINT [FK_List_SingleValue_List_Single] FOREIGN KEY([_Id])
        ///REFERENCES [dbo].[Li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_SingleValue {
            get {
                return ResourceManager.GetString("Table_List_SingleValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_String](
        ///	[_Id] [bigint] IDENTITY(1,1) NOT NULL,
        ///	[_DataObjectTypeId] [smallint] NOT NULL,
        ///	[ObjectId] [bigint] NOT NULL,
        ///	[ObjectRevisionId] [int] NOT NULL,
        ///	[_DataObjectFieldId] [int] NOT NULL,
        /// CONSTRAINT [PK_List_String] PRIMARY KEY CLUSTERED 
        ///(
        ///	[_Id] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///ALTER TABLE [dbo].[List_String]  WITH CHECK ADD  CONSTRA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_String {
            get {
                return ResourceManager.GetString("Table_List_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[List_StringValue](
        ///	[_Id] [bigint] NOT NULL,
        ///	[_Index] [int] NOT NULL,
        ///	[Value] [ntext] NULL,
        ///	 CONSTRAINT [PK_List_StringValue] PRIMARY KEY NONCLUSTERED 
        ///(
        ///	[_Id] ASC,
        ///	[_Index] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///
        ///GO
        ///
        ///ALTER TABLE [dbo].[List_StringValue]  WITH CHECK ADD  CONSTRAINT [FK_List_StringValue_List_String] FOREIGN KEY([_Id])
        ///REFERENCES [dbo].[L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table_List_StringValue {
            get {
                return ResourceManager.GetString("Table_List_StringValue", resourceCulture);
            }
        }
    }
}
